various updates, primarily updating genius to the latest

diff --git a/truecrypt/truecrypt.SlackBuild b/truecrypt/truecrypt.SlackBuild
--- a/truecrypt/truecrypt.SlackBuild
+++ b/truecrypt/truecrypt.SlackBuild
@@ -19,13 +19,13 @@ PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  SLKCFLAGS="-static -O2 -march=i486 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  SLKCFLAGS="-static -O2 -march=i686 -mtune=i686"
   LIBDIRSUFFIX=""
 elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+  SLKCFLAGS="-static -O2 -fPIC"
   LIBDIRSUFFIX="64"
 fi
 if [ ! -f ${CWD}/TrueCrypt\ $VERSION\ Source.tar.gz ] ; then
@@ -81,9 +81,7 @@ find . \
 
 make WX_ROOT=${TMP}/$WXWINDOWS-$WXWINDOWS_VERSION/ wxbuild
 
-CFLAGS="$SLKCFLAGS" \
-CXXFLAGS="$SLKCFLAGS" \
-make WXSTATIC=1 || echo "$0: compile failed"
+make WXSTATIC=1 TC_EXTRA_FLAGS="$SLKCFLAGS" || echo "$0: compile failed"
 mkdir -p $PKG/usr/bin
 cp -a Main/truecrypt $PKG/usr/bin/
 
